site_name: Learn with Arafat

theme:
  name: material

nav:
  - Home: index.md
  - Complexity and Computability Theory:
      - Deterministic Space Hierarchy Theorem: complexity_and_computability_theory/space_hierarchy.md
